DEFAULT_DATACONTRACT_NAMESPACE = "http://www.visioninternet.com"
API_NAME_PREFIX = "vision"
PARAM_METHOD_KEY = "_method"
PARAM_APP_KEY_KEY = "_app_key"
PARAM_FORMAT_KEY = "_format"
PARAM_TIMESTAMP_KEY = "_timestamp"
PARAM_VERSION_KEY = "_v"
PARAM_SIGN_KEY = "_sign"
MaxPageSize = 100
ArrayConcatChar = ";"
FieldConcatChar = ","
DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'